server:
  port: 3000

management:
  port: 3010

database:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1/syeftipay
  username: {username}
  password: {password}

logging:
  file: service.log

flyway:
  enabled: false

spring.jackson.serialization.write_dates_as_timestamps: false